version: 1.0.0.{build}
os: Visual Studio 2017

environment:
  ASPNETCORE_ENVIRONMENT: appveyor
  COVERALLS_REPO_TOKEN:
    secure: b7oQan0UI46v0UpNxYemWB8wAjVN/P0vmFKQgZIf2hAxI6e8zoYhvcSkt5gqYTIz
init:
  - git config --global core.autocrlf input

dotnet_csproj:
  patch: true
  file: 'build\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
  - dotnet tool install -g coveralls.net

build_script:
  - dotnet pack EntityFrameworkCore.CommandQuery.sln --configuration Release --include-symbols --include-source

test_script:
  - dotnet test ".\test\EntityFrameworkCore.CommandQuery.Tests\EntityFrameworkCore.CommandQuery.Tests.csproj" --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_test:
  - csmacnz.coveralls.exe --opencover --input ".\test\EntityFrameworkCore.CommandQuery.Tests\coverage.opencover.xml"

artifacts:
- path: artifacts\*.nupkg
  name: Packages

deploy:
- provider: Environment
  name: MyGet