version: 1.0.0.{build}
os: Visual Studio 2017

environment:
  ASPNETCORE_ENVIRONMENT: appveyor

init:
  - git config --global core.autocrlf input

dotnet_csproj:
  patch: true
  file: 'build\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
  - dotnet pack EntityFrameworkCore.CommandQuery.sln --configuration Release --include-symbols --include-source 

test_script:
  - dotnet test test\EntityFrameworkCore.CommandQuery.Tests\EntityFrameworkCore.CommandQuery.Tests.csproj --configuration Release

artifacts:
- path: artifacts\*.nupkg
  name: Packages

deploy:
- provider: Environment
  name: MyGet